[package]
name = "tmux-load-avg"
version = "0.1.0"
authors = ["Daniel Parker <danpker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "^0"
colored = "^2"
